# Generated by Django 2.2.3 on 2019-07-08 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
            ],
            options={
                'verbose_name': '垃圾类型分类表',
                'verbose_name_plural': '垃圾类型分类表',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='垃圾图片')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('garbage_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.GarbageCategory', verbose_name='垃圾类型类')),
            ],
            options={
                'verbose_name': '图片类',
                'verbose_name_plural': '图片类',
            },
        ),
    ]
