# Generated by Django 2.2.3 on 2019-07-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garbagecategory',
            options={'verbose_name': '垃圾类别表', 'verbose_name_plural': '垃圾类别表'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '图片表', 'verbose_name_plural': '图片表'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='garbage_category',
        ),
        migrations.AddField(
            model_name='garbagecategory',
            name='desc',
            field=models.CharField(max_length=1024, null=True, verbose_name='描述'),
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('desc', models.CharField(max_length=1024, null=True, verbose_name='描述')),
                ('garbage_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.GarbageCategory', verbose_name='垃圾类型类')),
            ],
            options={
                'verbose_name': '物品类别表',
                'verbose_name_plural': '物品类别表',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='goods_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.GoodsCategory', verbose_name='物品类别'),
        ),
    ]
